version: '3'
services: 
    xnat-web:
       build: ./tomcat
       ports:
        - "8081:8080"
        - "8104:8104"
       volumes:
         - ./webapps:/opt/tomcat/webapps
         - ./plugins:/data/xnat/home/plugins
         - /var/run/docker.sock:/var/run/docker.sock
         - ./logs/tomcat:/opt/tomcat/logs
         - ./logs/xnat:/data/xnat/home/logs
         - ./auth-provider.properties:/data/xnat/home/config/auth/auth-provider.properties
       expose:
        - "8080"
       links:
        - xnat-db    
    xnat-db:
       build: ./postgres
       expose:
         - "5432"
       volumes:
         - ./postgres-data:/var/lib/postgresql/data
    xnat-nginx:
       build: ./nginx
       ports:
        - "80:80"
        - "443:443"
       volumes:
          - ./logs/nginx:/var/log/nginx
       expose: 
          - "80"
       links:
          - xnat-web

    prometheus:
       image: prom/prometheus
       volumes:
            - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
       command:
            - '-config.file=/etc/prometheus/prometheus.yaml'
       ports:
            - '9090:9090'
       links:
            - cadvisor
    cadvisor:
        image: google/cadvisor
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        ports:
        - "8082:8080"        
        expose:
          - 8082
